# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rsolr"
  s.version = "1.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Mitchell", "Jeremy Hinegardner", "Mat Brown", "Mike Perham", "Nathan Witmer", "Peter Kieltyka", "Randy Souza", "shairon toledo", "shima", "Chris Beer", "Jonathan Rochkind"]
  s.date = "2011-11-09"
  s.description = "RSolr aims to provide a simple and extensible library for working with Solr"
  s.email = "goodieboy@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "VERSION",
    "lib/rsolr-direct.rb",
    "lib/rsolr.rb",
    "lib/rsolr/char.rb",
    "lib/rsolr/client.rb",
    "lib/rsolr/connection.rb",
    "lib/rsolr/error.rb",
    "lib/rsolr/response.rb",
    "lib/rsolr/uri.rb",
    "lib/rsolr/xml.rb"
  ]
  s.homepage = "http://github.com/mwmitchell/rsolr"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A Ruby client for Apache Solr"
  s.test_files = ["spec/api/char_spec.rb", "spec/api/client_spec.rb", "spec/api/connection_spec.rb", "spec/api/error_spec.rb", "spec/api/pagination_spec.rb", "spec/api/rsolr_spec.rb", "spec/api/uri_spec.rb", "spec/api/xml_spec.rb", "spec/spec_helper.rb", "Rakefile", "tasks/spec.rake", "tasks/rdoc.rake"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<builder>, ["= 3.0.0"])
      s.add_development_dependency(%q<jeweler>, ["= 1.6.4"])
      s.add_development_dependency(%q<rake>, ["= 0.9.2"])
      s.add_development_dependency(%q<rdoc>, ["= 3.9.4"])
      s.add_runtime_dependency(%q<builder>, [">= 2.1.2"])
    else
      s.add_dependency(%q<builder>, ["= 3.0.0"])
      s.add_dependency(%q<jeweler>, ["= 1.6.4"])
      s.add_dependency(%q<rake>, ["= 0.9.2"])
      s.add_dependency(%q<rdoc>, ["= 3.9.4"])
      s.add_dependency(%q<builder>, [">= 2.1.2"])
    end
  else
    s.add_dependency(%q<builder>, ["= 3.0.0"])
    s.add_dependency(%q<jeweler>, ["= 1.6.4"])
    s.add_dependency(%q<rake>, ["= 0.9.2"])
    s.add_dependency(%q<rdoc>, ["= 3.9.4"])
    s.add_dependency(%q<builder>, [">= 2.1.2"])
  end
end

